kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: couchbase-pvc
  namespace: spring-couchbase-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: thin